# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coupon_couponrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bely',
            field=models.IntegerField(default=100),
        ),
    ]
